{
  "openapi": "3.0.0",
  "info": {
    "title": "DB_ECOMMERCE",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:8000",
      "variables": {}
    }
  ],
  "paths": {
    "/users": {
      "post": {
        "tags": [
          "USER"
        ],
        "summary": "create new user",
        "operationId": "createnewuser",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/createnewuserrequest"
                  },
                  {
                    "example": {
                      "username": "Vinicio Chavarria",
                      "email": "vichavarria21@gmail.com",
                      "password": "12345678"
                    }
                  }
                ]
              },
              "example": {
                "username": "Vinicio Chavarria",
                "email": "vichavarria21@gmail.com",
                "password": "12345678"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/users/1": {
      "get": {
        "tags": [
          "USER"
        ],
        "summary": "Get products in car by user id",
        "operationId": "Getproductsincarbyuserid",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOm51bGwsImxhc3RuYW1lIjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJWaW5pY2lvIENoYXZhcnJpYSIsImVtYWlsIjoidmljaGF2YXJyaWEyMUBnbWFpbC5jb20iLCJpYXQiOjE2ODYzODE3MDEsImV4cCI6MTY4NjM5OTcwMX0.Ppv9PSnXM2oagRAd11VAf3o3eK7cOpXnSfBFmAAPHW1_vKLXyNHQOz6VLBQ7BwVPmNa7F1Gjl6d0vuPlgMgLcQ"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/user/orders/1": {
      "get": {
        "tags": [
          "USER"
        ],
        "summary": "Get orders by users id",
        "operationId": "Getordersbyusersid",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOm51bGwsImxhc3RuYW1lIjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJWaW5pY2lvIENoYXZhcnJpYSIsImVtYWlsIjoidmljaGF2YXJyaWEyMUBnbWFpbC5jb20iLCJpYXQiOjE2ODYzODE3MDEsImV4cCI6MTY4NjM5OTcwMX0.Ppv9PSnXM2oagRAd11VAf3o3eK7cOpXnSfBFmAAPHW1_vKLXyNHQOz6VLBQ7BwVPmNa7F1Gjl6d0vuPlgMgLcQ"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/users/login": {
      "post": {
        "tags": [
          "USER"
        ],
        "summary": "Login",
        "operationId": "Login",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/LoginRequest"
                  },
                  {
                    "example": {
                      "email": "vichavarria21@gmail.com",
                      "password": "12345678"
                    }
                  }
                ]
              },
              "example": {
                "email": "vichavarria21@gmail.com",
                "password": "12345678"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/products": {
      "post": {
        "tags": [
          "Products"
        ],
        "summary": "Create Product",
        "operationId": "CreateProduct",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOm51bGwsImxhc3RuYW1lIjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJWaW5pY2lvIENoYXZhcnJpYSIsImVtYWlsIjoidmljaGF2YXJyaWEyMUBnbWFpbC5jb20iLCJpYXQiOjE2ODYzODE3MDEsImV4cCI6MTY4NjM5OTcwMX0.Ppv9PSnXM2oagRAd11VAf3o3eK7cOpXnSfBFmAAPHW1_vKLXyNHQOz6VLBQ7BwVPmNa7F1Gjl6d0vuPlgMgLcQ"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "encoding": {},
              "schema": {
                "required": [
                  "image",
                  "name",
                  "description",
                  "price",
                  "userId"
                ],
                "type": "object",
                "properties": {
                  "image": {
                    "type": "string",
                    "format": "binary"
                  },
                  "name": {
                    "type": "string",
                    "example": "dise√±o svg"
                  },
                  "description": {
                    "type": "string",
                    "example": "dibujo cool"
                  },
                  "price": {
                    "type": "integer",
                    "format": "int32",
                    "example": 20
                  },
                  "userId": {
                    "type": "integer",
                    "format": "int32",
                    "example": 1
                  }
                }
              }
            }
          },
          "required": false
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Get products mayores a cero",
        "operationId": "Getproductsmayoresacero",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOm51bGwsImxhc3RuYW1lIjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJWaW5pY2lvIENoYXZhcnJpYSIsImVtYWlsIjoidmljaGF2YXJyaWEyMUBnbWFpbC5jb20iLCJpYXQiOjE2ODYzODE3MDEsImV4cCI6MTY4NjM5OTcwMX0.Ppv9PSnXM2oagRAd11VAf3o3eK7cOpXnSfBFmAAPHW1_vKLXyNHQOz6VLBQ7BwVPmNa7F1Gjl6d0vuPlgMgLcQ"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/products/1": {
      "put": {
        "tags": [
          "Products"
        ],
        "summary": "Edit description product",
        "operationId": "Editdescriptionproduct",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/productincar/products": {
      "post": {
        "tags": [
          "ProductInCar"
        ],
        "summary": "add to card",
        "operationId": "addtocard",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOm51bGwsImxhc3RuYW1lIjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJWaW5pY2lvIENoYXZhcnJpYSIsImVtYWlsIjoidmljaGF2YXJyaWEyMUBnbWFpbC5jb20iLCJpYXQiOjE2ODYzODE3MDEsImV4cCI6MTY4NjM5OTcwMX0.Ppv9PSnXM2oagRAd11VAf3o3eK7cOpXnSfBFmAAPHW1_vKLXyNHQOz6VLBQ7BwVPmNa7F1Gjl6d0vuPlgMgLcQ"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/addtocardrequest"
                  },
                  {
                    "example": {
                      "carId": 1,
                      "productId": 2,
                      "price": 20
                    }
                  }
                ]
              },
              "example": {
                "carId": 1,
                "productId": 2,
                "price": 20
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/orders": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "Create Order",
        "operationId": "CreateOrder",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOm51bGwsImxhc3RuYW1lIjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJWaW5pY2lvIENoYXZhcnJpYSIsImVtYWlsIjoidmljaGF2YXJyaWEyMUBnbWFpbC5jb20iLCJpYXQiOjE2ODYzNzY1MzIsImV4cCI6MTY4NjM3NjgzMn0.7Mi6H9n8hRYe37mDvTlXC4copN7GpviyN710Nmfzz2aBKIxhgL3cMM7ESp8ReNIW2xRrRZJDR5g-YeogloiiVg"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreateOrderRequest"
                  },
                  {
                    "example": {
                      "userId": 1,
                      "totalPrice": 100
                    }
                  }
                ]
              },
              "example": {
                "userId": 1,
                "totalPrice": 100
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/orders/3": {
      "put": {
        "tags": [
          "Orders"
        ],
        "summary": "Completed Order",
        "operationId": "CompletedOrder",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CompletedOrderRequest"
                  },
                  {
                    "example": {
                      "carId": 1,
                      "email": "vichavarria21@gmail.com"
                    }
                  }
                ]
              },
              "example": {
                "carId": 1,
                "email": "vichavarria21@gmail.com"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/productInOrder/orders": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "Add products in order",
        "operationId": "Addproductsinorder",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/AddproductsinorderRequest"
                  },
                  {
                    "example": {
                      "orderId": 3,
                      "productId": 2,
                      "price": 40,
                      "quantity": 1
                    }
                  }
                ]
              },
              "example": {
                "orderId": 3,
                "productId": 2,
                "price": 40,
                "quantity": 1
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "createnewuserrequest": {
        "title": "createnewuserrequest",
        "required": [
          "username",
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "username": "Vinicio Chavarria",
          "email": "vichavarria21@gmail.com",
          "password": "12345678"
        }
      },
      "LoginRequest": {
        "title": "LoginRequest",
        "required": [
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "email": "vichavarria21@gmail.com",
          "password": "12345678"
        }
      },
      "addtocardrequest": {
        "title": "addtocardrequest",
        "required": [
          "carId",
          "productId",
          "price"
        ],
        "type": "object",
        "properties": {
          "carId": {
            "type": "integer",
            "format": "int32"
          },
          "productId": {
            "type": "integer",
            "format": "int32"
          },
          "price": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "carId": 1,
          "productId": 2,
          "price": 20
        }
      },
      "CreateOrderRequest": {
        "title": "CreateOrderRequest",
        "required": [
          "userId",
          "totalPrice"
        ],
        "type": "object",
        "properties": {
          "userId": {
            "type": "integer",
            "format": "int32"
          },
          "totalPrice": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "userId": 1,
          "totalPrice": 100
        }
      },
      "CompletedOrderRequest": {
        "title": "CompletedOrderRequest",
        "required": [
          "carId",
          "email"
        ],
        "type": "object",
        "properties": {
          "carId": {
            "type": "integer",
            "format": "int32"
          },
          "email": {
            "type": "string"
          }
        },
        "example": {
          "carId": 1,
          "email": "vichavarria21@gmail.com"
        }
      },
      "AddproductsinorderRequest": {
        "title": "AddproductsinorderRequest",
        "required": [
          "orderId",
          "productId",
          "price",
          "quantity"
        ],
        "type": "object",
        "properties": {
          "orderId": {
            "type": "integer",
            "format": "int32"
          },
          "productId": {
            "type": "integer",
            "format": "int32"
          },
          "price": {
            "type": "integer",
            "format": "int32"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "orderId": 3,
          "productId": 2,
          "price": 40,
          "quantity": 1
        }
      }
    }
  },
  "tags": [
    {
      "name": "USER"
    },
    {
      "name": "Products"
    },
    {
      "name": "ProductInCar"
    },
    {
      "name": "Orders"
    }
  ]
}